### ISSUE TITLE
Script does not merge config file changes.

### ISSUE THREAD

**Issue by mysterious-static** [velinath/trinity-updater#1]
The script should add new config options and comment out removed config options, but should leave modified config options as the modified value.

I have looked into `merge` and `diff` but it looks like this may need a custom solution with `sed`, `cut`, or `awk`.

The last few characters in an uncommented line that sets a variable will always be `= X`, where `X` is the value of the variable.

First shot:

``` bash
while read -r newline; do
    if [[ ${newline:0:1} == "#" ]]; then
        continue
    fi
    newline_varname=`echo $newline | sed "s/ = /|/" | cut -d '|' -f 1`
    while read -r oldline; do
        if [[ ${oldline:0:1} == "#" ]]; then
            continue
        fi
        oldline_varname=`echo $oldline | sed "s/ = /|/" | cut -d '|' -f 1`
        if [[ $newline_varname == $oldline_varname ]]; then
            echo $oldline >> $SERVERDIR/etc/worldserver.conf.new
            continue 2
        fi
    done < $SERVERDIR/etc/worldserver.conf.dist
    echo $newline >> $SERVERDIR/etc/worldserver.conf.new
done < $SERVERDIR/etc/worldserver.conf
```

Testing would be appreciated. The snippet should be nondestructive and should output to `$SERVERDIR/etc/worldserver.conf.new`.

This does not remove old config lines that don't match anything. Input from TC devs would be appreciated as to whether this would negatively impact server performance in any way other than passing useless variables.

**Comment by velinath** [comment]
there is probably a way to condense the `sed | cut` into 1 `sed`

**Comment by mysterious-static** [comment]
Right now it doesn't seem like it's ever outputting the old variables. Don't know why.

**Comment by velinath** [comment]
whitespace

```bash
`echo $oldline | sed "s/ *$//" | cut -d '=' -f 1`
```

**Comment by mysterious-static** [comment]
``` bash
while read -r newline; do
    if [[ ${newline:0:1} == "#" ]] || [[ -z $newline ]]; then
        continue
    fi
    newline_varname=`echo $newline | sed "s/ *$//" | cut -d '=' -f 1`
    while read -r oldline; do
        if [[ ${oldline:0:1} == "#" ]] || [[ -z $oldline ]]; then
            continue
        fi
        oldline_varname=`echo $oldline | sed "s/ *$//" | cut -d '=' -f 1`
        if [[ $newline_varname == $oldline_varname ]]; then
            echo $oldline >> $SERVERDIR/etc/worldserver.conf.new
            continue 2
        fi
    done < $SERVERDIR/etc/worldserver.conf
    echo $newline >> $SERVERDIR/etc/worldserver.conf.new
done < $SERVERDIR/etc/worldserver.conf.dist
```

the above code seems to perform:
- adds new server variables to file
- removes whitespace lines and comments
- keeps old config values if the server variable already existed
- does not remove old config values

**Comment by mysterious-static** [comment]
runs awful as we get further down in the file, as one might expect

we could use a counter to count lines @ last match then use `tail -n +$count` to start the inner loop but I'm not sure what kind of performance gain we'd see and I'm very lazy
